general {
    lock_cmd = echo "no lock"
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# Tier 1 — Dim monitors
listener {
    timeout = 240
    on-timeout = sh -c 'ddcutil --sleep-multiplier=0.1 --display 1 setvcp 10 10; sleep 0.2; ddcutil --sleep-multiplier=0.1 --display 2 setvcp 10 10'

    on-resume = sh -c 'ddcutil --sleep-multiplier=0.1 --display 1 setvcp 10 100; sleep 0.2; ddcutil --sleep-multiplier=0.1 --display 2 setvcp 10 100'
}

# Tier 2 — Turn displays off
listener {
    timeout = 300
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}