
wallpaper {
    monitor = DP-2
    path = ~/Pictures/Wallpapers/space_upper.png
    fit_mode = cover
}

wallpaper {
    monitor = DP-1
    path = ~/Pictures/Wallpapers/space_lower.png
    fit_mode = cover
}

splash = false
